<a href="https://colab.research.google.com/github/Satyajit4698/ann/blob/master/Deeplearning_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import files
upload=files.upload()

Saving Churn_Modelling.csv to Churn_Modelling (2).csv


In [0]:
!ls

'Churn_Modelling (1).csv'   Churn_Modelling.csv
'Churn_Modelling (2).csv'   sample_data


In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [0]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
len(data)

10000

In [0]:
x=data.iloc[:,3:13].values
y=data.iloc[:,13].values

In [0]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [0]:
label_Encoder_x_1=LabelEncoder()
x[:,1]=label_Encoder_x_1.fit_transform(x[:,1])
label_Encoder_x_2=LabelEncoder()
x[:,2]=label_Encoder_x_2.fit_transform(x[:,2])
transformer=ColumnTransformer(transformers=[('Geography',OneHotEncoder(),[1])],remainder='passthrough')
x=transformer.fit_transform(x.tolist())
x=x.astype('float64')

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [0]:
cls=Sequential()
cls.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=12))
cls.add(Dense(output_dim=6,init='uniform',activation='relu'))
cls.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))
cls.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=12, units=6, kernel_initializer="uniform")`
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  after removing the cwd from sys.path.


In [0]:
cls.fit(x_train,y_train,batch_size=20,epochs=100)




Epoch 1/100





8000/8000 [==============================] - 10s 1ms/step - loss: 0.5299 - acc: 0.7951
Epoch 2/100
8000/8000 [==============================] - 1s 159us/step - loss: 0.4350 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.4304 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 162us/step - loss: 0.4281 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.4250 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 162us/step - loss: 0.4220 - acc: 0.8006
Epoch 7/100
8000/8000 [==============================] - 1s 164us/step - loss: 0.4199 - acc: 0.8203
Epoch 8/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.4179 - acc: 0.8220
Epoch 9/100
8000/8000 [==============================] - 1s 158us/step - loss: 0.4160 - acc: 0.8255
Epoch 10/100
8000/8000 [==============================] - 1s 155us/step - loss: 0.4148 - acc:

In [0]:
y_pred=cls.predict(x_test)
y_pred

array([[0.22706333],
       [0.3235489 ],
       [0.16932428],
       ...,
       [0.20248419],
       [0.1637153 ],
       [0.10603154]], dtype=float32)

In [0]:
y_pred=(y_pred>0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [0]:
len(y_pred)

2000

In [0]:
from sklearn.metrics import confusion_matrix

In [0]:
cn=confusion_matrix(y_test,y_pred)
cn

array([[1541,   54],
       [ 265,  140]])

In [0]:
from sklearn.metrics import accuracy_score


In [0]:
ac=accuracy_score(y_test,y_pred)
ac

0.8405